on: [push]
name: CHICO CI
jobs:
  build_and_test:
    name: CHICO CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Run tests."
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: "Convert a hexadecimal number. (short)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- -c EA1573
      - name: "Convert a hexadecimal number. (long)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- --cox EA1573
      - name: "Convert a hexadecimal number. (nkd)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- cox EA1573
      - name: "Convert a binary number. (short)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- -b 1010101
      - name: "Convert a binary number. (long)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- --bin 1010101
      - name: "Convert a binary number. (nkd)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- bin 1010101
      - name: "Convert a base-8 number to a base-10 number. (long)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- --oct 1565
      - name: "Convert a base-8 number to a base-10 number. (short)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- -o 1565
      - name: "Convert a base-8 number to a base-10 number. (nkd)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- oct 1565
      - name: "Convert a base-10 number to a base-16 number."
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- --xoc --dec 42
      - name: "Convert a base-10 number to a base-2 number."
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- --yoc --dec 66
     
